version: "3"
name: "todolistnextjs"
services:
  app:
    build:
      context: .
      target: dev
    command: npm run dev
    environment:
      DATABASE_URL: "${INNER_DATABASE_URL}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/data
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres: # database url must have 'postgres' as the host, not 'localhost'
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data